version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docker/sedona-spark-jupyterlab
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /zeppelin
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
