name: Scala and Java build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
      
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - spark: 3.4.0
            scala: 2.13.8
            jdk: '8'
            skipTests: ''
          - spark: 3.4.0
            scala: 2.12.15
            jdk: '8'
            skipTests: ''
          - spark: 3.4.0
            scala: 2.12.15
            jdk: '11'
            skipTests: ''
          - spark: 3.3.0
            scala: 2.12.15
            jdk: '8'
            skipTests: ''            
          - spark: 3.2.3
            scala: 2.12.15
            jdk: '8'
            skipTests: ''            
          - spark: 3.1.2
            scala: 2.12.15
            jdk: '8'
            skipTests: ''            
          - spark: 3.0.3
            scala: 2.12.15
            jdk: '8'
            skipTests: ''

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - env:
        SPARK_VERSION: ${{ matrix.spark }}
        SCALA_VERSION: ${{ matrix.scala }}
        SKIP_TESTS: ${{ matrix.skipTests }}
      run: |
        SPARK_COMPAT_VERSION="3.0"
        if [ ${SPARK_VERSION:2:1} -gt "3" ]; then
          SPARK_COMPAT_VERSION=${SPARK_VERSION:0:3}
        fi
        mvn -q clean install -Dspark=${SPARK_COMPAT_VERSION} -Dscala=${SCALA_VERSION:0:4} -Dspark.version=${SPARK_VERSION} ${SKIP_TESTS}
    - run: mkdir staging
    - run: cp spark-shaded/target/sedona-*.jar staging
    - run: |
        [ -d "flink-shaded/target/" ] && cp flink-shaded/target/sedona-*.jar staging 2>/dev/null || true
    - uses: actions/upload-artifact@v2
      with:
        name: generated-jars
        path: staging
